name: Auto-release version

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/CHANGELOG.md'
      - 'static/**'
      - 'src/**'

jobs:
  build-assets:
    name: Build assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
    
      - name: Install dependencies
        run: npm install

      - name: Build
        id: build
        run: npm run build

      - name: Zip raw source code
        run: zip -r source.zip . -x "node_modules/*" ".git/*" "dist/*" "artifacts/*" ".github/*" ".coverage/*" ".husky/*" ".vscode/*"

      - name: Pack directory to zip
        id: pack
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'dist/'
          zipFilePath: 'artifacts/dist.zip'

      - name: Upload zipped artifacts
        id: upload-zip-artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-dist-zip
          path: artifacts/dist.zip

      - name: Upload raw source
        id: upload-raw-source
        uses: actions/upload-artifact@v4
        with:
          name: source-zip
          path: source.zip

  build-signed-crx:
    needs: build-assets
    name: Build signed CRX
    runs-on: ubuntu-latest
    steps:
      - name: Download zipped artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact-dist-zip
          path: artifacts

      - name: Build offline crx
        id: build-crx
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: artifacts/dist.zip
          crxFilePath: artifacts/storygraph-enhancement-tools.crx
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

      - name: Upload CRX artifact
        id: upload-crx-artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-crx
          path: artifacts/storygraph-enhancement-tools.crx

      - name: Upload CRX to Chrome Webstore
        run: npx chrome-webstore-upload-cli@4 --source artifacts/dist.zip
        env:
          EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CHROME_DEV_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CHROME_DEV_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.CHROME_DEV_REFRESH_TOKEN }}
          PUBLISHER_ID: ${{ secrets.CHROME_DEV_PUBLISHER_ID }}

  build-signed-xpi:
    needs: build-assets
    name: Build signed XPI
    runs-on: ubuntu-latest
    steps:
      - name: Download zipped artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact-dist-zip
          path: ./

      - name: Download source artifact
        uses: actions/download-artifact@v4
        with:
          name: source-zip
          path: ./

      - name: Unzip source and dist
        run: unzip dist.zip -d unzipped-dist

      - name: Sign Firefox XPI for distribution
        run: |
          npx web-ext@10 sign --channel listed --source-dir unzipped-dist --upload-source-code source.zip --timeout 1200000 --artifacts-dir artifacts/
        env:
          WEB_EXT_API_KEY: ${{ secrets.FIREFOX_JWT_ISSUER }}
          WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}

      - name: Upload XPI artifact
        id: upload-xpi-artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-xpi
          path: artifacts/*.xpi

  create-release:
    needs:
      - build-assets
      - build-signed-crx
      - build-signed-xpi
    if: success() || failure()
    name: Create tag and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from CHANGELOG.md
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          path: ./docs/CHANGELOG.md

      - name: Push tag with correct version
        id: push_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.changelog_reader.outputs.version }}
          release_branches: main

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: artifact-*
          merge-multiple: true

      - name: Create a new release
        uses: softprops/action-gh-release@v2
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.changelog_reader.outputs.version }}
          name: ${{ steps.changelog_reader.outputs.version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          draft: false
          files: |
            artifacts/*.zip
            artifacts/*.crx
            artifacts/*.xpi
