name: Run Tests

# These rules will run the workflow when a commit is pushed to the main branch, or a PR against the main branch is opened or updated
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# This concurrency mode will cancel in-progress workflows if a new commit is pushed   
concurrency: 
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Schema cannot be parsed fro this link, at least with Manifest v3
      # - name: Validate manifest.json
      #   uses: cardinalby/schema-validator-action@v3
      #   with:
      #     file: 'static/manifest.json'
      #     schema: 'https://json.schemastore.org/webextension.json'

      # If you want to use coveralls to report the coverage produced by c8, uncomment this step
      # - name: Coveralls
      #   uses: coverallsapp/github-action@v2