name: Run Tests

# These rules will run the workflow when a commit is pushed to the main branch, or a PR against the main branch is opened or updated
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# This concurrency mode will cancel in-progress workflows if a new commit is pushed   
concurrency: 
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test and validate manifest
        uses: ./.github/workflows/actions/test
